import json,pytest
from tensorfem.mesh_project import load_mesh_project,run_mesh_project
def project(mesh):return {'schema':'tensorfem.mesh-project.v1','name':'bar','units':{'length':'m','force':'N','stress':'Pa','displacement':'m'},'model':{'name':'bar','element_type':'truss2d'},'mesh':mesh,'sets':{'node':{'left':[1],'right':[2]},'element':{'all':[1]},'surface':{}},'materials':[{'name':'mat','model':'linear_elastic','properties':{'young':200.}}],'sections':[{'name':'sec','element_set':'all','material':'mat','properties':{'area':2.}}],'step':{'name':'static','procedure':'linear_static'},'loads':[{'name':'pull','type':'nodal','target':'right','dof':1,'value':40.}],'constraints':[{'name':'fix','type':'displacement','target':'left','dofs':[1,2],'value':0},{'name':'guide','type':'displacement','target':'right','dofs':[2],'value':0}],'outputs':[{'name':'field','fields':['U','RF','S','E']}]}
def test_external_json_mesh_end_to_end_and_replay(tmp_path):
 mesh={'nodes':[{'id':1,'coordinates':[0.,0.]},{'id':2,'coordinates':[2.,0.]}],'elements':[{'id':1,'type':'truss2d','connectivity':[1,2]}]};(tmp_path/'mesh.json').write_text(json.dumps(mesh));p=tmp_path/'project.json';p.write_text(json.dumps(project({'file':'mesh.json'})))
 a=run_mesh_project(p,tmp_path/'runs');b=run_mesh_project(p,tmp_path/'runs');assert abs(a['displacement'][2]-.2)<1e-12 and b['metadata']['replayed']
def test_unknown_topology_path_and_code_fail_closed(tmp_path):
 base=project({'nodes':[{'id':1,'coordinates':[0,0]},{'id':2,'coordinates':[1,0]}],'elements':[{'id':1,'type':'truss2d','connectivity':[1,3]}]});p=tmp_path/'p.json';p.write_text(json.dumps(base))
 with pytest.raises(ValueError,match='topology'):load_mesh_project(p)
 base=project({'file':'../escape.json'});p.write_text(json.dumps(base))
 with pytest.raises(ValueError,match='escapes'):load_mesh_project(p)
 base=project({'nodes':[],'elements':[]});base['python']='import os';p.write_text(json.dumps(base))
 with pytest.raises(ValueError,match='unknown'):load_mesh_project(p)
def test_inline_tet4_linear_dispatch(tmp_path):
 p={'schema':'tensorfem.mesh-project.v1','name':'tet','units':{'length':'m','force':'N','stress':'Pa','displacement':'m'},'model':{'name':'tet','element_type':'tet4_linear'},'mesh':{'nodes':[{'id':1,'coordinates':[0,0,0]},{'id':2,'coordinates':[1,0,0]},{'id':3,'coordinates':[0,1,0]},{'id':4,'coordinates':[0,0,1]}],'elements':[{'id':1,'type':'tet4_linear','connectivity':[1,2,3,4]}]},'sets':{'node':{'origin':[1],'x':[2],'y':[3],'z':[4]},'element':{'all':[1]},'surface':{'face':[{'element':1,'face':1}]}},'materials':[{'name':'mat','model':'linear_elastic','properties':{'young':200000.,'poisson':.3}}],'sections':[{'name':'solid','element_set':'all','material':'mat','properties':{}}],'step':{'name':'static','procedure':'linear_static'},'loads':[{'name':'pull','type':'nodal','target':'x','dof':1,'value':400/6}],'constraints':[{'name':'o','type':'displacement','target':'origin','dofs':[1,2,3],'value':0},{'name':'xg','type':'displacement','target':'x','dofs':[2,3],'value':0},{'name':'yg','type':'displacement','target':'y','dofs':[1,3],'value':0},{'name':'zg','type':'displacement','target':'z','dofs':[1,2],'value':0}],'outputs':[{'name':'field','fields':['U','RF','S','E']}]}
 path=tmp_path/'tet.json';path.write_text(json.dumps(p));r=run_mesh_project(path,tmp_path/'runs')
 assert abs(r['displacement'][3]-.002)<1e-12 and abs(r['fields']['stress'][0][0]-400)<1e-9
def test_external_hex8_and_steady_thermal_projects(tmp_path):
 nodes=[[0,0,0],[1,0,0],[1,1,0],[0,1,0],[0,0,1],[1,0,1],[1,1,1],[0,1,1]]
 mesh={'nodes':[{'id':i+1,'coordinates':x} for i,x in enumerate(nodes)],'elements':[{'id':1,'type':'hex8_linear','connectivity':list(range(1,9))}]};(tmp_path/'hexmesh.json').write_text(json.dumps(mesh))
 sets={'node':{'x0':[1,4,5,8],'y0':[1,2,5,6],'z0':[1,2,3,4],'x1':[2,3,6,7]},'element':{'all':[1]},'surface':{}}
 hp={'schema':'tensorfem.mesh-project.v1','name':'hex','units':{'length':'m','force':'N','stress':'Pa','displacement':'m'},'model':{'name':'cube','element_type':'hex8_linear'},'mesh':{'file':'hexmesh.json'},'sets':sets,'materials':[{'name':'m','model':'linear_elastic','properties':{'young':200000.,'poisson':.3}}],'sections':[{'name':'s','element_set':'all','material':'m','properties':{}}],'step':{'name':'s','procedure':'linear_static'},'loads':[{'name':'p','type':'nodal','target':'x1','dof':1,'value':100.}],'constraints':[{'name':'x','type':'displacement','target':'x0','dofs':[1],'value':0},{'name':'y','type':'displacement','target':'y0','dofs':[2],'value':0},{'name':'z','type':'displacement','target':'z0','dofs':[3],'value':0}],'outputs':[{'name':'o','fields':['U','RF','S','E']}]};hpath=tmp_path/'hex.json';hpath.write_text(json.dumps(hp));hr=run_mesh_project(hpath,tmp_path/'runs')
 assert max(abs(hr['displacement'][3*(i-1)]-.002) for i in sets['node']['x1'])<1e-10
 tmesh={'nodes':[{'id':1,'coordinates':[0.]},{'id':2,'coordinates':[2.]}],'elements':[{'id':1,'type':'thermal_line2','connectivity':[1,2]}]};(tmp_path/'thermalmesh.json').write_text(json.dumps(tmesh))
 tp={'schema':'tensorfem.mesh-project.v1','name':'thermal','units':{'length':'m','temperature':'K','heat_rate':'W','conductivity':'W/(m*K)'},'model':{'name':'rod','element_type':'thermal_line2'},'mesh':{'file':'thermalmesh.json'},'sets':{'node':{'hot':[1],'cold':[2]},'element':{'all':[1]},'surface':{}},'materials':[{'name':'m','model':'steady_thermal','properties':{'conductivity':5.,'density':3.,'specific_heat':7.}}],'sections':[{'name':'s','element_set':'all','material':'m','properties':{'thickness':2.}}],'step':{'name':'s','procedure':'linear_static'},'loads':[],'constraints':[{'name':'h','type':'temperature','target':'hot','dofs':[1],'value':100.},{'name':'c','type':'temperature','target':'cold','dofs':[1],'value':40.}],'outputs':[{'name':'o','fields':['TEMP','FLUX']}]};tpath=tmp_path/'thermal.json';tpath.write_text(json.dumps(tp));tr=run_mesh_project(tpath,tmp_path/'runs')
 assert tr['displacement']==[100.,40.] and abs(abs(tr['reaction'][0])-300.)<1e-10
def test_unknown_physics_combinations_fail_closed(tmp_path):
 p=project({'nodes':[{'id':1,'coordinates':[0,0]},{'id':2,'coordinates':[1,0]}],'elements':[{'id':1,'type':'truss2d','connectivity':[1,2]}]});p['outputs'][0]['fields']=['TEMP'];path=tmp_path/'bad.json';path.write_text(json.dumps(p))
 with pytest.raises(ValueError,match='output'):load_mesh_project(path)
